 import { Recipe, Region, DietaryConstraint } from "./types";
 
 export const regions: Region[] = [
   {
     id: "north-india",
     name: "North India",
     description: "Rich, creamy curries & tandoor specialties",
     icon: "🍛",
   },
   {
     id: "south-india",
     name: "South India",
     description: "Coconut-based, tangy & aromatic dishes",
     icon: "🥥",
   },
   {
     id: "mediterranean",
     name: "Mediterranean",
     description: "Olive oil, herbs & fresh ingredients",
     icon: "🫒",
   },
   {
     id: "east-asian",
     name: "East Asian",
     description: "Umami-rich, balanced & fermented flavors",
     icon: "🥢",
   },
   {
     id: "middle-eastern",
     name: "Middle Eastern",
     description: "Aromatic spices & hearty grains",
     icon: "🧆",
   },
   {
     id: "latin-american",
     name: "Latin American",
     description: "Bold, vibrant & spice-forward cuisine",
     icon: "🌶️",
   },
 ];
 
 export const dietaryConstraints: DietaryConstraint[] = [
   { id: "vegan", name: "Vegan", icon: "🌱" },
   { id: "vegetarian", name: "Vegetarian", icon: "🥬" },
   { id: "jain", name: "Jain", icon: "☸️" },
   { id: "gluten-free", name: "Gluten-Free", icon: "🌾" },
   { id: "keto", name: "Keto", icon: "🥑" },
   { id: "low-fat", name: "Low Fat", icon: "💧" },
   { id: "dairy-free", name: "Dairy-Free", icon: "🥛" },
   { id: "nut-free", name: "Nut-Free", icon: "🥜" },
 ];
 
 export const sampleRecipes: Recipe[] = [
   {
     id: "vegan-butter-chicken",
     title: "Vegan Butter Chicken",
     description:
       "A flavor-optimized regeneration of the classic North Indian butter chicken. This version uses cashew cream and soy curls to perfectly replicate the rich, creamy texture while maintaining 98% of the original flavor compounds.",
     matchScore: 98,
     region: "North India",
     dietaryTags: ["Vegan", "Dairy-Free"],
     totalTime: 45,
     difficulty: "Medium",
     servings: 4,
     flavorProfile: {
       sweet: 35,
       salty: 45,
       sour: 20,
       bitter: 10,
       umami: 75,
       spicy: 55,
     },
     ingredients: [
       { name: "Soy Curls", amount: "200g", note: "Replaces chicken for texture retention", isRegenerated: true },
       { name: "Cashew Cream", amount: "1 cup", note: "Replaces heavy cream with molecular similarity", isRegenerated: true },
       { name: "Tomato Puree", amount: "400g" },
       { name: "Coconut Oil", amount: "3 tbsp", note: "Replaces butter for richness", isRegenerated: true },
       { name: "Kashmiri Red Chili", amount: "2 tsp" },
       { name: "Garam Masala", amount: "1.5 tsp" },
       { name: "Ginger-Garlic Paste", amount: "2 tbsp" },
       { name: "Cumin Seeds", amount: "1 tsp" },
       { name: "Coriander Powder", amount: "1 tsp" },
       { name: "Turmeric", amount: "0.5 tsp" },
       { name: "Fenugreek Leaves", amount: "1 tbsp" },
       { name: "Coconut Sugar", amount: "1 tsp", note: "Balances acidity", isRegenerated: true },
       { name: "Salt", amount: "to taste" },
       { name: "Fresh Cilantro", amount: "for garnish" },
     ],
     steps: [
       {
         id: 1,
         instruction: "Rehydrate soy curls in warm vegetable broth for 10 minutes. Drain and squeeze out excess liquid.",
         duration: 10,
         isCritical: false,
       },
       {
         id: 2,
         instruction: "Blend raw cashews with 1 cup warm water until completely smooth. This cashew cream is the molecular substitute for dairy cream.",
         duration: 5,
         isCritical: true,
       },
       {
         id: 3,
         instruction: "Heat coconut oil in a deep pan. Add cumin seeds and let them splutter for 30 seconds.",
         duration: 2,
         isCritical: false,
       },
       {
         id: 4,
         instruction: "Add ginger-garlic paste and sauté until the raw smell disappears (about 2 minutes).",
         duration: 2,
         isCritical: false,
       },
       {
         id: 5,
         instruction: "Add all dry spices: Kashmiri chili, coriander, turmeric. Toast for 60 seconds until fragrant. This blooms the essential oils.",
         duration: 1,
         isCritical: true,
       },
       {
         id: 6,
         instruction: "Pour in the tomato puree and cook on medium heat for 8-10 minutes until oil separates from the masala.",
         duration: 10,
         isCritical: true,
       },
       {
         id: 7,
         instruction: "Reduce heat to low. Slowly stir in the cashew cream. Do not boil after adding to prevent splitting.",
         duration: 3,
         isCritical: true,
       },
       {
         id: 8,
         instruction: "Add the rehydrated soy curls and garam masala. Simmer gently for 10 minutes to let flavors meld.",
         duration: 10,
         isCritical: false,
       },
       {
         id: 9,
         instruction: "Finish with crushed fenugreek leaves and coconut sugar. Adjust salt. The sugar balances the tomato acidity.",
         duration: 2,
         isCritical: false,
       },
       {
         id: 10,
         instruction: "Garnish with fresh cilantro. Serve hot with naan or basmati rice.",
         isCritical: false,
       },
     ],
   },
   {
     id: "keto-tikka-masala",
     title: "Keto Tikka Masala",
     description:
       "A low-carb regeneration of chicken tikka masala using cauliflower and a coconut cream base. Maintains the signature smoky char and creamy gravy profile.",
     matchScore: 94,
     region: "North India",
     dietaryTags: ["Keto", "Low-Carb", "Gluten-Free"],
     totalTime: 55,
     difficulty: "Medium",
     servings: 4,
     flavorProfile: {
       sweet: 20,
       salty: 50,
       sour: 25,
       bitter: 15,
       umami: 80,
       spicy: 60,
     },
     ingredients: [
       { name: "Cauliflower Florets", amount: "500g", note: "Char-grilled for protein-like texture", isRegenerated: true },
       { name: "Full-Fat Coconut Cream", amount: "400ml", isRegenerated: true },
       { name: "Tomato Paste", amount: "3 tbsp" },
       { name: "Ghee", amount: "4 tbsp" },
       { name: "Tikka Spice Blend", amount: "3 tbsp" },
       { name: "Greek Yogurt", amount: "1/2 cup" },
       { name: "Ginger-Garlic Paste", amount: "2 tbsp" },
       { name: "Erythritol", amount: "1 tsp", note: "Zero-glycemic sweetener", isRegenerated: true },
       { name: "Salt & Pepper", amount: "to taste" },
     ],
     steps: [
       { id: 1, instruction: "Marinate cauliflower in yogurt, tikka spices, and salt for 30 minutes.", duration: 30, isCritical: false },
       { id: 2, instruction: "Char-grill or broil cauliflower until edges are blackened.", duration: 12, isCritical: true },
       { id: 3, instruction: "Sauté ginger-garlic paste in ghee, add tomato paste and spices.", duration: 5, isCritical: false },
       { id: 4, instruction: "Add coconut cream and simmer for 10 minutes.", duration: 10, isCritical: false },
       { id: 5, instruction: "Add charred cauliflower, finish with erythritol to balance.", duration: 5, isCritical: false },
     ],
   },
   {
     id: "jain-palak-paneer",
     title: "Jain Palak Paneer",
     description:
       "A Jain-compliant version of palak paneer that eliminates onion and garlic while using asafoetida and ginger to recreate the depth of flavor.",
     matchScore: 96,
     region: "North India",
     dietaryTags: ["Jain", "Vegetarian", "Gluten-Free"],
     totalTime: 35,
     difficulty: "Easy",
     servings: 3,
     flavorProfile: {
       sweet: 15,
       salty: 40,
       sour: 30,
       bitter: 45,
       umami: 55,
       spicy: 35,
     },
     ingredients: [
       { name: "Fresh Spinach", amount: "400g" },
       { name: "Paneer", amount: "250g" },
       { name: "Asafoetida (Hing)", amount: "1/4 tsp", note: "Replaces onion-garlic flavor compounds", isRegenerated: true },
       { name: "Fresh Ginger", amount: "1 inch", note: "Enhanced to compensate for missing alliums", isRegenerated: true },
       { name: "Green Chilies", amount: "2" },
       { name: "Cumin Seeds", amount: "1 tsp" },
       { name: "Cream", amount: "3 tbsp" },
       { name: "Ghee", amount: "2 tbsp" },
       { name: "Salt", amount: "to taste" },
     ],
     steps: [
       { id: 1, instruction: "Blanch spinach in boiling water for 2 minutes. Shock in ice bath.", duration: 5, isCritical: true },
       { id: 2, instruction: "Blend spinach with green chilies into a smooth puree.", duration: 3, isCritical: false },
       { id: 3, instruction: "Heat ghee, add asafoetida and cumin. Let asafoetida bloom for 30 seconds.", duration: 1, isCritical: true },
       { id: 4, instruction: "Add ginger and sauté briefly. Pour in spinach puree.", duration: 5, isCritical: false },
       { id: 5, instruction: "Simmer for 5 minutes. Add paneer cubes and cream.", duration: 8, isCritical: false },
     ],
   },
 ];
 
 export const processingSteps = [
   { id: 1, text: "Fetching Base Recipe...", icon: "📖" },
   { id: 2, text: "Analyzing Cultural Constraints...", icon: "🌍" },
   { id: 3, text: "Mapping Flavor Compounds...", icon: "🧪" },
   { id: 4, text: "Optimizing Ingredient Substitutions...", icon: "🔄" },
   { id: 5, text: "Finalizing Instructions...", icon: "✨" },
 ];